#include <pthread.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

#define NUM_THREADS 5

void *printHello(void *threadid)
{
    long thread_id = (long)threadid;
    printf("Hello World! It's me, thread #%ld!\n", thread_id);
    pthread_exit((void *)(thread_id + 1));
}

int main(int argc, char *argv[])
{

    pthread_t threads[NUM_THREADS];
    int return_code;
    long thread_index;

    for (thread_index = 0; thread_index < NUM_THREADS; thread_index++)
    {
        printf("In main: creating thread %ld\n", thread_index);
        return_code = pthread_create(&threads[thread_index],
                                     NULL, printHello, (void *)thread_index);
        if (return_code)
        {
            printf("Error: return code generated by callding pthread_create() is %d\n", return_code);
            exit(thread_index + 1);
        }
    }

    void *status[NUM_THREADS];
    for (int i = 0; i < NUM_THREADS; i++)
    {
        pthread_join(threads[i], &status[i]);
        printf("Thread %d was completed! Status %d\n", i, (int)status[i]);
    }

    pthread_exit(NULL);
}